### ISSUE TITLE
Appears to hang when generating JS source 

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#142] opened 2015-03-06 17:54 UTC
When I use the baselline template to generate documentation for my library it appears to hang. I ran it with --debug and the problem appears to be with the generation of the page that shows the source of the JS file. One or two of the files are very large. If I omit the largest one it does eventually finish (500 seconds). If I click on any of the source links it also takes quite a while to render.

I wanted to try generating without the source links like this:
"sourceFiles": {
// Set to true to generate pretty-printed HTML versions of the source files, and to link to
// the pretty-printed files from the documentation. Set to false to omit the pretty-printed
// source files and the links to these files.
"generate": false,
// Set to true to include a single link to the source file in the documentation, near the
// top of the page. Set to false to include a source-file link with each symbol in the
// documentation.
"singleLink": false
}

but that made no difference at all. It still generated the source links etc. I must be misunderstanding this section of the config.

As an aside, I cannot understand the description of "singleLink" at all. What is the effect of this option?

**Comment by hegemonic** [comment] 2015-03-06 22:52
I've run Baseline against some very large source files without running into this problem. Can you point me to a source file that's not working for you?

Setting `sourceFiles.generate` to `false` should indeed prevent the source files from being generated. I'll see whether I can reproduce that issue.

If `sourceFiles.singleLink` is `true`, each page only includes one link to the source file, near the top of the page. If it's `false`, we provide a link to the source file alongside every single method, property, etc.

**Comment by kpturner** [comment] 2015-03-07 00:08
It seems strange because I know the -c option is telling jsdoc to use my config.json because if I deliberately put a syntax error in it, it fails.  Likewise, in order to get it to complete (despite taking about 8 minutes) I am using an excludepattern to excluse the very big file.  BUT, it completely ignores these sourceFiles section of the json.  Also, in debug, it reports the config settings being used and they are not the ones in the file specified by the -c option.  I use generate:false,singleLink:true and I still get a singleLink 

The file I have a problem with (I don't think it is hanging - just taking a long time) is an old legacy script file just under 30000 lines of code.  I am going to leave it to run overnight and see if it finishes rather than hangs.

**Comment by hegemonic** [comment] 2015-03-07 00:40
Ah, I think I know what's going on. Right now, you need to provide a separate JSON file with the Baseline config options. So your `config.json` file should include something like this:

```json
{
  "templates": {
    "baseline": "baseline.json"
  }
}
```

And then `baseline.json` would look like this:

```json
{
  "sourceFiles": {
    "generate": false,
    "singleLink": true
  }
}
```

I've been meaning to change this so you can just embed the Baseline options in JSDoc's config file. I filed #145 as a reminder. Until I fix that one, you'll have to use a separate file.

I'll be curious to hear whether the 30,000-line file ever finishes. Would it be possible to share that file, either publicly or privately, for debugging purposes?

**Comment by kpturner** [comment] 2015-03-07 11:45
OK I have managed to get it to not generate source using the instructions above and it runs through nicely.  If I do allow it to generate source, then it doesn't hang - but it does take a very long time (I left it over night).  To be honest, this old file should be omitted from my documentation anyway - but I am happy to send you a copy privately if you want to play with it.  How should I do that?

**Comment by kpturner** [comment] 2015-03-07 12:14
A question about the source file links.  I think these are very useful, but the only thing I have noticed is that the links appear to want to try to take you to a tag. In other words, if I click on a source link for a method that starts at line 100 then the URL looks like it is going to try to position me to line 100 when I click the link. The trouble is, it doesn't position me to line 100.  Regardless of the URL, I am always position at the top of the source file.

**Comment by hegemonic** [comment] 2015-03-07 17:59
You can email the source file to jeffrey.l.williams@gmail.com. I'll see if I can figure out why it takes so long to generate the output file.

Could you please file a separate issue for the source-link bug?

**Comment by kpturner** [comment] 2015-03-07 18:57
OK - emailed

**Comment by kpturner** [comment] 2015-03-07 19:19
If my config.json says:

"templates": {
    	"baseline": "baseline.json"
 }

then where is jsdoc going to look for the baseline.json file ?

**Comment by hegemonic** [comment] 2015-03-07 20:53
I believe it'll look for `baseline.json` in whatever your current working directory was when you started JSDoc.

This problem is caused by the fact that the HTML beautifier is very slow. If you set `beautify` to `false` in the Baseline options file, this issue goes away.

I haven't been able to find a better HTML beautifier than the one I'm using, so I may just set a size limit above which we won't attempt to beautify the file.

**Comment by hegemonic** [comment] 2015-05-11 23:16
Fixed on master. We now beautify output files that are <128 KB. Larger files are not beautified.

**Closed by hegemonic** 2015-05-11 23:16 UTC
Labels: bug
